{
    "name":"My GYM",
    "version":"1.0",
    "summary":"My GYM",
    "description":"My GYM new addons in odoo 18.0",
    "category":"Tools",
    "website":"",
    "author":"Khaled Mohamed Abdo",
    "license":"",
    "application":True,
    "installable":True,
    "auto_install":False,
    "depends":["base"],
    "data":[
        'security/ir.model.access.csv',
        'data/sequance.xml',
        'views/base_menu.xml',
        'views/caption_menu_view.xml',
    ],
    "demo":[],
    "qweb":[],
    "license":"LGPL-3",
}